# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(699, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.turnonButton = QtWidgets.QPushButton(self.centralwidget)
        self.turnonButton.setGeometry(QtCore.QRect(190, 360, 101, 71))
        self.turnonButton.setObjectName("turnonButton")
        self.turnoffButton = QtWidgets.QPushButton(self.centralwidget)
        self.turnoffButton.setGeometry(QtCore.QRect(400, 360, 101, 71))
        self.turnoffButton.setObjectName("turnoffButton")
        self.Lamp = QtWidgets.QPushButton(self.centralwidget)
        self.Lamp.setGeometry(QtCore.QRect(290, 130, 93, 91))
        self.Lamp.setStyleSheet("\n"
"background-color: rgb(127,127,127);\n"
"border-style:none;\n"
"border:1px solid #3f3f3f; \n"
"\n"
"padding:5px;\n"
"min-height:20px;\n"
"border-radius:45px;\n"
"")
        self.Lamp.setText("")
        self.Lamp.setFlat(True)
        self.Lamp.setObjectName("Lamp")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 699, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.turnonButton.setText(_translate("MainWindow", "开灯"))
        self.turnoffButton.setText(_translate("MainWindow", "关灯"))
